CREATE TABLE [dbo].[DemoTable1]
(
[Id] [int] NOT NULL IDENTITY(1, 1),
[UserId] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DemoTable1] ADD CONSTRAINT [PK__DemoTabl__3214EC0762E89AE4] PRIMARY KEY CLUSTERED ([Id]) ON [PRIMARY]
GO
